# .github/workflows/deploy-to-nordicway.yml
name: Deploy to Nordicway

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      ref:
        description: "Branch, tag, or SHA to deploy (empty = default branch)"
        required: false
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    concurrency:
      group: nordicway-${{ inputs.environment }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Uncomment if you build assets for your theme/plugin
      # - name: Build Theme
      #   working-directory: wp-content/themes/masterofmagic
      #   run: |
      #     npm ci
      #     npm run build

      # - name: Build Plugin
      #   working-directory: wp-content/plugins/masterofmagic-blocks
      #   run: |
      #     npm ci
      #     npm run build

      - name: Prepare deploy artifact
        run: |
          mkdir -p artifact/wp-content/themes/masterofmagic
          mkdir -p artifact/wp-content/plugins/masterofmagic-blocks

          rsync -av wp-content/themes/masterofmagic/ artifact/wp-content/themes/masterofmagic \
            --exclude=node_modules --exclude=.git --exclude=.github --exclude=.gitignore --exclude=package*.json --exclude=composer.* --exclude=resources

          rsync -av wp-content/plugins/masterofmagic-blocks/ artifact/wp-content/plugins/masterofmagic-blocks \
            --exclude=node_modules --exclude=.git --exclude=.github --exclude=.gitignore --exclude=package*.json --exclude=composer.* --exclude=resources

      - name: Deploy to Nordicway via rsync
        env:
          HOST: ${{ secrets.NORDICWAY_SSH_HOST }}
          USER: ${{ secrets.NORDICWAY_SSH_USERNAME }}
          PORT: ${{ secrets.NORDICWAY_SSH_PORT }}
          DEST: ${{ secrets.NORDICWAY_DEST_PATH }}
        run: |
          echo "Deploying to $USER@$HOST:$DEST"
          mkdir -p ~/.ssh
          echo "${{ secrets.NORDICWAY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $PORT $HOST >> ~/.ssh/known_hosts

          RSYNC_RSH="ssh -i ~/.ssh/id_rsa -p $PORT -o StrictHostKeyChecking=yes"
          rsync -az --delete artifact/wp-content/themes/masterofmagic/ "$USER@$HOST:$DEST/themes/masterofmagic/"
          rsync -az --delete artifact/wp-content/plugins/masterofmagic-blocks/ "$USER@$HOST:$DEST/plugins/masterofmagic-blocks/"

      - name: Post-deploy sanity check
        run: |
          echo "✅ Deployment completed to ${{ inputs.environment }}"
