# .github/workflows/deploy-to-nordicway.yml
name: Deploy to Nordicway

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ref:
        required: false
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options: [staging, production]
      ref:
        description: "Branch, tag, or SHA to deploy (empty = default branch)"
        required: false
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    concurrency:
      group: nordicway-${{ inputs.environment }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # --- OPTIONAL: build steps for your theme/plugin(s) ---
      # - name: Build Theme (example)
      #   working-directory: wp-content/themes/masterofmagic
      #   run: |
      #     npm ci
      #     npm run build
      #
      # - name: Build Plugin (example)
      #   working-directory: wp-content/plugins/masterofmagic-blocks
      #   run: |
      #     npm ci
      #     npm run build

      - name: Prepare deploy artifact (only the parts you control)
        run: |
          mkdir -p artifact/wp-content/themes
          mkdir -p artifact/wp-content/plugins

          # copy all themes you maintain
          rsync -av wp-content/themes/ artifact/wp-content/themes \
            --exclude='**/node_modules/**' \
            --exclude='**/.git/**' \
            --exclude='**/.github/**' \
            --exclude='**/.gitignore' \
            --exclude='**/composer.*' \
            --exclude='**/package*.json' \
            --exclude='**/webpack.*' \
            --exclude='**/vite.*' \
            --exclude='**/resources/**' \
            --exclude='**/README.md'

          # copy all plugins you maintain (if any)
          if [ -d "wp-content/plugins" ]; then
            rsync -av wp-content/plugins/ artifact/wp-content/plugins \
              --exclude='**/node_modules/**' \
              --exclude='**/.git/**' \
              --exclude='**/.github/**' \
              --exclude='**/.gitignore' \
              --exclude='**/composer.*' \
              --exclude='**/package*.json' \
              --exclude='**/webpack.*' \
              --exclude='**/vite.*' \
              --exclude='**/resources/**' \
              --exclude='**/README.md'
          fi

      - name: Write SSH key & known_hosts
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NORDICWAY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p ${{ secrets.NORDICWAY_SSH_PORT }} ${{ secrets.NORDICWAY_SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Preflight (ensure destination subfolders exist)
        shell: bash
        run: |
          ssh -i ~/.ssh/deploy_key -p ${{ secrets.NORDICWAY_SSH_PORT }} \
            ${{ secrets.NORDICWAY_SSH_USERNAME }}@${{ secrets.NORDICWAY_SSH_HOST }} \
            "mkdir -p '${{ secrets.NORDICWAY_DEST_PATH }}/themes' '${{ secrets.NORDICWAY_DEST_PATH }}/plugins' && \
             ls -lah '${{ secrets.NORDICWAY_DEST_PATH }}'"

      - name: Deploy THEMES via rsync (clean)
        env:
          HOST: ${{ secrets.NORDICWAY_SSH_HOST }}
          USER: ${{ secrets.NORDICWAY_SSH_USERNAME }}
          PORT: ${{ secrets.NORDICWAY_SSH_PORT }}
          DEST: ${{ secrets.NORDICWAY_DEST_PATH }}
        shell: bash
        run: |
          if [ -d "artifact/wp-content/themes" ]; then
            rsync -az --delete \
              -e "ssh -i ~/.ssh/deploy_key -p $PORT -o StrictHostKeyChecking=yes" \
              artifact/wp-content/themes/ "$USER@$HOST:$DEST/themes/"
          else
            echo "No themes to deploy."
          fi

      - name: Deploy PLUGINS via rsync (clean)
        env:
          HOST: ${{ secrets.NORDICWAY_SSH_HOST }}
          USER: ${{ secrets.NORDICWAY_SSH_USERNAME }}
          PORT: ${{ secrets.NORDICWAY_SSH_PORT }}
          DEST: ${{ secrets.NORDICWAY_DEST_PATH }}
        shell: bash
        run: |
          if [ -d "artifact/wp-content/plugins" ] && [ "$(ls -A artifact/wp-content/plugins)" ]; then
            rsync -az --delete \
              -e "ssh -i ~/.ssh/deploy_key -p $PORT -o StrictHostKeyChecking=yes" \
              artifact/wp-content/plugins/ "$USER@$HOST:$DEST/plugins/"
          else
            echo "No plugins to deploy."
          fi

      - name: Post-deploy sanity check
        shell: bash
        run: |
          ssh -i ~/.ssh/deploy_key -p ${{ secrets.NORDICWAY_SSH_PORT }} \
            ${{ secrets.NORDICWAY_SSH_USERNAME }}@${{ secrets.NORDICWAY_SSH_HOST }} \
            "echo '✅ Deployed to ${{ inputs.environment }}';
             echo '--- themes ---';  ls -lah '${{ secrets.NORDICWAY_DEST_PATH }}/themes' || true;
             echo '--- plugins ---'; ls -lah '${{ secrets.NORDICWAY_DEST_PATH }}/plugins' || true;
             php -v || true"
