# .github/workflows/deploy-to-nordicway.yml
name: Deploy to Nordicway

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ref:
        required: false
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options: [staging, production]
      ref:
        description: "Branch, tag, or SHA to deploy (empty = default branch)"
        required: false
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    concurrency:
      group: nordicway-${{ inputs.environment }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # --- OPTIONAL: build steps for your theme/plugin(s) ---
      # - name: Build Theme
      #   working-directory: wp-content/themes/masterofmagic
      #   run: |
      #     npm ci
      #     npm run build
      #
      # - name: Build Plugin
      #   working-directory: wp-content/plugins/masterofmagic-blocks
      #   run: |
      #     npm ci
      #     npm run build

      - name: Prepare deploy artifact (whole wp-content minus uploads/runtime/dev junk)
        run: |
          mkdir -p artifact/wp-content
          rsync -av wp-content/ artifact/wp-content \
            --exclude='uploads/**' \
            --exclude='upgrade/**' \
            --exclude='cache/**' \
            --exclude='wflogs/**' \
            --exclude='*.map' \
            --exclude='**/node_modules/**' \
            --exclude='**/.git/**' \
            --exclude='**/.github/**' \
            --exclude='**/.gitignore' \
            --exclude='**/composer.*' \
            --exclude='**/package*.json' \
            --exclude='**/webpack.*' \
            --exclude='**/vite.*' \
            --exclude='**/resources/**' \
            --exclude='**/README.md'

      - name: Write SSH key & known_hosts
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NORDICWAY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p ${{ secrets.NORDICWAY_SSH_PORT }} ${{ secrets.NORDICWAY_SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Preflight (ensure destination exists)
        shell: bash
        run: |
          ssh -i ~/.ssh/deploy_key -p ${{ secrets.NORDICWAY_SSH_PORT }} \
            ${{ secrets.NORDICWAY_SSH_USERNAME }}@${{ secrets.NORDICWAY_SSH_HOST }} \
            "mkdir -p '${{ secrets.NORDICWAY_DEST_PATH }}' && ls -lah '${{ secrets.NORDICWAY_DEST_PATH }}' || true"

      - name: Deploy wp-content via rsync over SSH (preserve uploads)
        env:
          HOST: ${{ secrets.NORDICWAY_SSH_HOST }}
          USER: ${{ secrets.NORDICWAY_SSH_USERNAME }}
          PORT: ${{ secrets.NORDICWAY_SSH_PORT }}
          DEST: ${{ secrets.NORDICWAY_DEST_PATH }}
        shell: bash
        run: |
          RSYNC_RSH="ssh -i ~/.ssh/deploy_key -p $PORT -o StrictHostKeyChecking=yes"
          # --delete keeps themes/plugins in sync BUT excludes protect uploads etc.
          rsync -az --delete \
            --exclude='uploads/**' \
            --exclude='upgrade/**' \
            --exclude='cache/**' \
            --exclude='wflogs/**' \
            artifact/wp-content/ "$USER@$HOST:$DEST/"

      - name: Post-deploy sanity check
        shell: bash
        run: |
          ssh -i ~/.ssh/deploy_key -p ${{ secrets.NORDICWAY_SSH_PORT }} \
            ${{ secrets.NORDICWAY_SSH_USERNAME }}@${{ secrets.NORDICWAY_SSH_HOST }} \
            "echo '✅ Deployed to ${{ inputs.environment }}';
             echo '--- wp-content ---'; ls -lah '${{ secrets.NORDICWAY_DEST_PATH }}';
             echo '--- themes ---';    ls -lah '${{ secrets.NORDICWAY_DEST_PATH }}/themes' || true;
             echo '--- plugins ---';   ls -lah '${{ secrets.NORDICWAY_DEST_PATH }}/plugins' || true;
             php -v || true"
