# .github/workflows/deploy-to-nordicway.yml
name: Deploy to Nordicway

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ref:
        required: false
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options: [staging]
      ref:
        description: 'Branch, tag, or SHA to deploy (empty = default branch)'
        required: false
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # --- OPTIONAL: build steps for your theme/plugin(s) ---
      # - name: Install and Build Theme
      #   working-directory: wp-content/themes/masterofmagic
      #   run: |
      #     npm ci
      #     npm run build
      #
      # - name: Install and Build Plugin
      #   working-directory: wp-content/plugins/masterofmagic-blocks
      #   run: |
      #     npm ci
      #     npm run build

      - name: Prepare deploy artifact (whole wp-content minus runtime/dev junk)
        run: |
          mkdir -p artifact/wp-content
          rsync -av wp-content/ artifact/wp-content \
            --exclude='uploads/**' \
            --exclude='upgrade/**' \
            --exclude='cache/**' \
            --exclude='wflogs/**' \
            --exclude='*.map' \
            --exclude='**/node_modules/**' \
            --exclude='**/.git/**' \
            --exclude='**/.github/**' \
            --exclude='**/.gitignore' \
            --exclude='**/composer.*' \
            --exclude='**/package*.json' \
            --exclude='**/webpack.*' \
            --exclude='**/vite.*' \
            --exclude='**/resources/**' \
            --exclude='**/README.md'

      # ⬇️ FTPS deploy (no SSH key)
      - name: Deploy wp-content via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ${{ secrets.FTP_SECURE == 'true' && 'ftps' || 'ftp' }}
          # deploy entire wp-content from the prepared artifact
          local-dir: artifact/wp-content/
          server-dir: ${{ secrets.FTP_DEST_PATH_STAGING }}
          # keep remote as-is (do NOT wipe), we exclude runtime dirs above
          dangerous-clean-slate: false
          exclude: |
            uploads/**
            upgrade/**
            cache/**
            wflogs/**
            **/node_modules/**
            **/.git/**
            **/.github/**

      - name: Post-deploy summary
        run: echo "Deployed wp-content to Nordicway (staging) via FTPS."
